src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as mviews
from editor import views as eviews
from files import views as fviews
from posts import views as pviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', mviews.index, name='index'),
    path('home/', mviews.home, name='home'),
    path('upnav/', mviews.refreshNav, name='nav'),
    path('uptagednav/', mviews.refreshtagedNav, name='tagednav'),
    path('upsearchnav/<path:cont>', mviews.refreshsearchNav, name='searcgnav'),
    path('upfile/', fviews.uploadPage, name='uploadpage'),
    path('download/<path:fp>', fviews.downFiles, name='download'),
    path('upload/', fviews.upload, name='upload'),
    path('files/<path:fp>/', fviews.viewFiles, name='viewfiles'),
    path('removefile/<path:fp>/', fviews.removeFile, name='removefile'),
    path('updatefile/<path:fp>/', fviews.updateFile, name='updatefile'),
    path('setpost/', pviews.setPost, name='setpost'),
    path('updatepost/<path:fp>/', pviews.updatePost, name='updatepost'),
    path('removepost/<path:fp>/', pviews.removePost, name='removepost'),
    path('validpost/', pviews.validPost, name='validpost'),
    path('savecache/', pviews.saveCache, name='savecache'),
    path('posts/', include('posts.urls')),
    path('preview/<path:route>', mviews.preview, name='preview'),
    path('preview_table/<path:route>', mviews.preview_table, name='preview_table'),
    path('edit/', include('editor.urls')),
]

src/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('<path:fp>/', views.viewPosts),
]

src/posts/models.py
from django.db import models

# Create your models here.

class myPost(models.Model):
    pname = models.CharField(
        max_length=100,
        help_text='Required. 100 characters or fewer.',
    )
    powner = models.CharField(
        max_length=200,
        help_text='Required. 200 characters or fewer.',
        default='admin',
    )
    pviewers = models.CharField(
        max_length=200,
        help_text='Required. 200 characters or fewer. Use `public` for all users.',
        default='private',
    )
    peditors = models.CharField(
        max_length=200,
        help_text='Required. 200 characters or fewer. Use `public` for all users.',
        default='private',
    )
    ptags = models.CharField(
        max_length=200,
        default='',
    )
    pdate = models.CharField(
        max_length=8,
    )
    pfeature = models.CharField(
        max_length=20,
        default='default',
    )
    purl = models.CharField(
        max_length=300,
        primary_key=True,
    )
    ppass = models.CharField(
        max_length=100,
        default='',
        blank=True
    )
    prank = models.IntegerField(
        default=0,
    )
    ptrace = models.IntegerField(
        default=1
    )

src/posts/forms.py
from django import forms

class PostInfoForm(forms.Form):
    powner = forms.CharField(max_length=200)
    pname = forms.CharField(max_length=200)
    pviewers = forms.CharField(max_length=200)
    peditors = forms.CharField(max_length=200)
    ptags = forms.CharField(max_length=200)
    pfeature = forms.CharField(max_length=20)
    pcontent = forms.CharField(max_length=65535, required=False)
    poverlap = forms.BooleanField(required=False)
    ppass = forms.CharField(max_length=100, required=False)
    prank = forms.IntegerField()
    ptrace = forms.IntegerField()

src/posts/views.py
#coding:utf-8
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseNotFound, HttpResponse
import os
# Create your views here.
import core
from .forms import PostInfoForm
from .models import myPost
post_basedir = os.path.join(os.path.dirname(core.settings.BASE_DIR), 'postbase/')
cache_basedir = os.path.join(os.path.dirname(core.settings.BASE_DIR), 'cache/')
import time
import codecs
from django.utils.encoding import smart_text

from django.views.decorators.csrf import csrf_exempt

def getDate():
    return time.strftime("%Y%m%d")

def handle_upload(request, form, basedir=post_basedir):
    info=None
    try:
        info = myPost()
        info.powner = form.cleaned_data.get('powner')
        info.pdate = getDate()
        info.pfeature = form.cleaned_data.get('pfeature')
        info.pname = form.cleaned_data.get('pname')
        info.pviewers = form.cleaned_data.get('pviewers')
        info.peditors = form.cleaned_data.get('peditors')
        info.ptags = form.cleaned_data.get('ptags')
        info.purl = '%s/%s/%s'%(info.powner, info.pfeature, info.pname)
        info.ppass = form.cleaned_data.get('ppass')
        info.prank = form.cleaned_data.get('prank')
        info.ptrace = form.cleaned_data.get('ptrace')
    except Exception:
        return None, False
    pdir1 = os.path.join(basedir, info.powner)
    if not os.path.exists(pdir1):
        try:
            os.mkdir(pdir1)
        except Exception:
            return None, False
    pdir2 = os.path.join(pdir1, info.pfeature)
    if not os.path.exists(pdir2):
        try:
            os.mkdir(pdir2)
        except Exception:
            return None, False
    pf = os.path.join(pdir2, info.pname)
    if not os.path.exists(pf):
        try:
            f = codecs.open(pf, 'w', 'UTF-8')
            f.close()
        except Exception:
            return None, False
    elif len(form.cleaned_data.get('pcontent'))>0:
        try:
            f = codecs.open(pf, 'w', 'UTF-8')
            f.write(form.cleaned_data.get('pcontent'))
            f.close()
        except Exception:
            return None, False
    return info, True


def setPost(request):
    return render(request, 'posts/postinfo.html', context={'have_source':False})

def updatePost(request, fp):
    if request.user.is_authenticated:
        try:
            mypost = myPost.objects.get(purl=fp)
        except Exception:
            return HttpResponseNotFound
        owner = mypost.powner
        editors = set(mypost.peditors.split())
        if ('unlimited' in editors or request.user.is_authenticated and ('public' in editors or request.user.username in editors or request.user.username==owner)):
            source_ponwer = mypost.powner
            file_name = mypost.pname
            feature_name = mypost.pfeature
            post_viewers = mypost.pviewers
            post_editors = mypost.peditors
            post_tags = mypost.ptags
            post_pass = mypost.ppass
            post_rank = mypost.prank
            post_trace = mypost.ptrace
            return render(request, 'posts/postinfo.html', context={'have_source':True, 'source_powner':source_ponwer, 'source_pname':file_name, 'source_pfeature':feature_name, 'post_viewers':post_viewers, 'post_editors':post_editors, 'post_tags':post_tags, 'post_pass':post_pass, 'post_rank':post_rank, 'post_trace':post_trace})
        else:
            return HttpResponseNotFound
    else:
        return redirect("/users/login/")



def validPost(request):
    ret = {'success':False, 'message':'', 'url':'/'}
    if not request.user.is_authenticated:
        ret['message']=u'你尚未登录，请转到主页登录后操作。'
    else:
        if request.method == 'POST':
            form = PostInfoForm(request.POST)
            if form.is_valid():
                info, is_success= handle_upload(request, form)
                viewers = set(info.pviewers.split())
                viewers.discard('private')
                viewers.discard(info.powner)
                editors = set(info.peditors.split())
                editors.discard('private')
                editors.discard(info.powner)
                if editors.issubset(viewers)==False:
                    ret['message']=u'拥有编辑权限的用户必须拥有浏览权限！'
                else:
                    if is_success==False:
                        ret['message']=u'初始化出错，请联系管理员。'
                    else:
                        try:
                            myPost.objects.get(purl=info.purl)
                        except Exception:
                            info.save()
                            ret['success'] = True
                            ret['url']='/edit/%s'%(info.purl)
                            ret['message'] = u'创建/更新成功'
                        else:
                            if form.cleaned_data.get('poverlap'):
                                info.save()
                                ret['success'] = True
                                ret['url']='/edit/%s'%(info.purl)
                            else:
                                ret['message']=u'这篇文章已经存在，如要更新请勾选overlap选项。'
            else:
                ret['message']=u'请确认输入了合适的标题，并填写了可见的用户；如果填写没有问题，请联系管理员排查错误。'
        else:
            ret = {'message', 'Stop hacking me!'}
    return JsonResponse(ret)
def saveCache(request):
    ret = {'success':False, 'message':'', 'url':'/'}
    if not request.user.is_authenticated:
        ret['message']=u'你尚未登录，请转到主页登录后操作。'
    else:
        if request.method == 'POST':
            form = PostInfoForm(request.POST)
            if form.is_valid():
                info, is_success= handle_upload(request, form, basedir=cache_basedir)
                if is_success==False:
                    ret['message']=u'初始化出错，请联系管理员。'
                else:
                    ret['success'] = True
            else:
                ret['message']=u'请确认输入了合适的标题，并填写了可见的用户；如果填写没有问题，请联系管理员排查错误。'
        else:
            ret = {'message', 'Stop hacking me!'}
    return JsonResponse(ret)

def extract_head_tail(content):
    head = ''
    end_pos = 0
    h_start = '<!-- HEAD DEFINATION, EDIT AFTER THIS LINE.'
    h_end = '-->'
    if content.startswith(h_start):
        end_pos = content.find(h_end)
        if end_pos!=-1:
            head = content[len(h_start):end_pos]
            end_pos += len(h_end)
        else:
            end_pos = len(h_start)
    while(end_pos<len(content) and (content[end_pos]=='\n' or content[end_pos]=='\r')):
        end_pos+=1
    content = h_start + '\n' + head.strip().rstrip() + '\n' + h_end + '\n' + content[end_pos:]
    
    tail = ''
    t_start = '<!--'
    t_end = 'TAIL DEFINATION, EDIT ABOVE THIS LINE. -->'
    while(content.endswith('\n') or content.endswith('\r')):
        content = content[:-1]
    st_pos = -1
    if content.endswith(t_end):
        st_pos = content.rfind(t_start)
        if st_pos!=-1:
            tail = content[st_pos+len(t_start):-len(t_end)]
            content = content[:st_pos]
    while(content.endswith('\n') or content.endswith('\r')):
        content = content[:-1]
    content = content + '\n\n' + t_start + '\n' + tail.strip().rstrip() + '\n' + t_end + '\n'
    return content, head, tail



def getPosts(request, fp):
    ret = {'success':0, 'message':''}
    if request.user.is_authenticated:
        try:
            mypost = myPost.objects.get(purl=fp)
        except Exception:
            ret['success'] = 1
            ret['message'] = u'不存在此文章！'
        viewers = set(mypost.pviewers.split())
        editors = set(mypost.peditors.split())
        owner = mypost.powner
        if ('unlimited' in editors or request.user.is_authenticated and ('public' in editors or request.user.username in editors or request.user.username==owner)):
            try:
                post_path = os.path.join(post_basedir, fp)
                f = codecs.open(post_path, 'r', 'UTF-8')
                content = ''.join(f.readlines())
                f.close()
                file_name = os.path.basename(post_path)
                content = smart_text(content)
                content, content_head, content_tail = extract_head_tail(content)
                ret['success']=2
                ret['post_owner']=owner
                ret['post_title']=file_name
                ret['post_viewers']=mypost.pviewers
                ret['post_editors']=mypost.peditors
                ret['post_content']=content
                ret['post_tags']=mypost.ptags
                ret['post_date']=mypost.pdate
                ret['post_feature']=mypost.pfeature
                ret['post_pass']=mypost.ppass
                ret['post_rank']=mypost.prank
                ret['post_trace']=mypost.ptrace
            except IOError:
                ret['success'] = 1
                ret['message'] = u'不存在此文章！'
        else:
            ret['success'] = 0
            ret['message'] = u'不存在此文章！'
    else:
        ret['success'] = 0
        ret['message'] = u'你尚未登录，请转到主页登录后操作。'
    return ret
def getCachedPosts(request, fp):
    ret = ''
    if request.user.is_authenticated:
        try:
            mypost = myPost.objects.get(purl=fp)
        except Exception:
            pass
        viewers = set(mypost.pviewers.split())
        editors = set(mypost.peditors.split())
        owner = mypost.powner
        if ('unlimited' in editors or request.user.is_authenticated and ('public' in editors or request.user.username in editors or request.user.username==owner)):
            try:
                post_path = os.path.join(cache_basedir, fp)
                f = codecs.open(post_path, 'r', 'UTF-8')
                content = ''.join(f.readlines())
                content, content_head, content_tail = extract_head_tail(content)
                f.close()
                file_name = os.path.basename(post_path)
                content = smart_text(content)
                ret=content
            except IOError:
                content, content_head, content_tail = extract_head_tail("")

templates/posts/post_passwd.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8" />
        <title>{{ post_title }}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'posts/css/stylesheet.css' %} " />
        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
        <link rel="shortcut icon" href="{% static 'main/images/siteicon.ico' %}">
        <link rel="bookmark" href="{% static 'main/images/siteicon.ico' %}">
        <style>
            .editormd-html-preview {
                width: 61.8%;
                margin: 0 auto;
            }
            body {
              opacity:1.0;
            }
        </style>
    </head>
    <body>
        <script src="{% static 'main/js/jquery.js' %} "></script>
        <script src="{% static 'editor/lib/marked.min.js' %}"></script>
        <script src="{% static 'editor/lib/prettify.min.js' %}"></script>

        <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
        <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
        <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
        <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
        <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>

        <script src="{% static 'editor/editormd.js' %}"></script>
        <script type="text/javascript">
            $(function() {
                var testEditormdView1;
                testEditormdView = editormd.markdownToHTML("test-editormd-view", {
                        // htmlDecode      : true,
                        htmlDecode      : "style,script",
                        //toc             : false,
                        tocm            : true,
                        //tocContainer    : "#custom-toc-container",
                        //gfm             : false,
                        //tocDropdown     : true,
                        // markdownSourceCode : true,
                        emoji           : true,
                        taskList        : true,
                        tex             : true,  // 默认不解析
                        flowChart       : true,  // 默认不解析
                        sequenceDiagram : true,  // 默认不解析
                    });

            });
        </script>
        <form action="" method="POST" style="display:none" id="forward_form">
            {% csrf_token %}
            <textarea name="pass" id="pass_ele"> </textarea>
        </form>
        <script>
            function StandardPost(url,pass){
                var temp_form = document.getElementById("forward_form");
                temp_form.action = url;
                var opt = document.getElementById("pass_ele");
                opt.value = pass;
                temp_form.appendChild(opt);
                temp_form.submit();
            }
            var r=prompt("{{ addtional_info }} 请输入文档所有者提供的验证信息：", "");
            if (r){
                StandardPost('{{ request_url | safe }}',r);
            }
        </script>

    </body>
</html>

templates/posts/postinfo.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
        <title>Post Settings</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Post Settings" />
        <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
        <meta name="author" content="Codrops" />
        <link rel="shortcut icon" href="{% static 'main/images/siteicon.ico' %}">
        <link rel="bookmark" href="{% static 'main/images/siteicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'users/css/demo.css' %} "/>
        <link rel="stylesheet" type="text/css" href="{% static 'users/css/style3.css' %} " />
		<link rel="stylesheet" type="text/css" href="{% static 'users/css/animate-custom.css' %} " />
        <style>
        .errorlist {
            color: red;
        }
        </style>
		<script src="{% static 'main/js/jquery.js' %} "></script>
        <script>
            function try_up(){
                $(document).ready(function(){
                    var formData = new FormData($('#up_form')[0]);
                    $('#el').html('Checking~');
                    $.ajax({
                            type: "POST",
                            url: "{% url 'validpost' %}",
                            data: formData,
                            contentType: false,
                            processData: false,
                            success: function (ret) {
                                if (ret['success']){
                                    window.location.href = ret['url']

                                }
                                else{
                                    $('#el').html(ret['message']);
                                }
                                return false;
                        }
                    })
                });
            }
        </script>
    </head>
    <body>
        <div class="container">
            <!-- Codrops top bar -->
            <div class="codrops-top">
                <span class="right">

                </span>
                <div class="clr"></div>
            </div><!--/ Codrops top bar -->
            <section>
                <div id="container_demo" >
                    <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
                    <div id="wrapper">
                        <div id="register" class="animate form">
                            <form id="up_form">
                                <h1> Post Settings </h1>
                                {% csrf_token %}
                                <p style="display:block">
                                    <label for="id_powner" class="uname" data-icon="e">所有者:</label>
                                    {% if have_source %}
                                    <input id="id_powner" name="powner" required="required" type="text" placeholder="请先登录！" value="{{ source_powner }}" readonly="readonly"/>
                                    {% else %}
                                    <input id="id_powner" name="powner" required="required" type="text" placeholder="请先登录！" value="{{ request.user.username }}" readonly="readonly"/>
                                    {% endif %}
                                </p>
                                <p>
                                    <label for="id_pname" class="uname" data-icon="e">标题:</label>
                                    {% if have_source %}
                                    <input id="id_pname" name="pname" required="required" type="text" placeholder="最重要的标题，必填！" value="{{ source_pname }}" readonly="readonly"/>
                                    {% else %}
                                    <input id="id_pname" name="pname" required="required" type="text" placeholder="最重要的标题，必填！" />
                                    {% endif %}
                                </p>
                                <p>
                                    <label for="id_pfeature" class="uname" data-icon="e">主题:</label>
                                    {% if have_source %}
                                    <input id="id_pfeature" name="pfeature" required="required" type="text" value="{{ source_pfeature }}" placeholder="文章标识，同名文章就用这个来区分了。" readonly="readonly"/>
                                    {% else %}
                                    <input id="id_pfeature" name="pfeature" required="required" type="text" value="default" placeholder="文章标识，同名文章就用这个来区分了。" />
                                    {% endif %}
                                </p>
                                <p>
                                    <label for="id_pviewers" class="uname" data-icon="u">浏览权限:</label>
                                    <input id="id_pviewers" name="pviewers" type="text" value={% if have_source %}"{{ post_viewers }}"{% else %}"private"{% endif %} placeholder="自己:`private`，公开:`public`，其他人:用户名，多种设置用空格隔开" />
                                </p>
                                <p>
                                    <label for="id_peditors" class="uname" data-icon="u">编辑权限:</label>
                                    <input id="id_peditors" name="peditors" type="text" value={% if have_source %}"{{ post_editors }}"{% else %}"private"{% endif %} placeholder="自己:`private`，公开:`public`，其他人:用户名，多种设置用空格隔开" />
                                </p>
                                <p>
                                    <label for="id_ptags" class="uname" data-icon="u">标签:</label>
                                    <input id="id_ptags" name="ptags" type="text" value={% if have_source %}"{{ post_tags }}"{% else %}"null"{% endif %} placeholder="给文章一些标签，方便自己归类，多个tag用竖线|隔开。" />
                                </p>
                                <p class="keeplogin">
                                    {% if have_source %}
                                    <input type="checkbox" name="poverlap" id="id_poverlap" checked="checked" style="opacity:0; position:absolute; left:9999px;"/>
                                    {% else %}
                                    <input type="checkbox" name="poverlap" id="id_poverlap"/>
                                    <label for="id_poverlap">Overlap(是要更新上面的文章吗？)</label>
                                    {% endif %}
                                </p>
                                <p class="signin button" >
                                    <img src="{% static 'main/images/submit_button.png' %}" height=auto width=30% onmousedown="try_up()">
                                </p>

                                <p>
                                        <label for="id_ppass" class="youpasswd" data-icon="p">验证码:</label>
                                        <input id="id_ppass" name="ppass" type="text" value={% if have_source %}"{{ post_pass }}"{% else %}""{% endif %} placeholder="如不需要密码，则不设置" />
                                </p>
                                <p>
                                        <label for="id_prank" class="uname" data-icon="u">排序优先级:</label>
                                        <input id="id_prank" name="prank" type="text" value={% if have_source %}"{{ post_rank }}"{% else %}"0"{% endif %} placeholder="默认0，越大越靠前" />
                                </p>
                                <p>
                                        <label for="id_ptrace" class="uname" data-icon="u">导航显示:</label>
                                        <input id="id_ptrace" name="ptrace" type="text" value={% if have_source %}"{{ post_trace }}"{% else %}"1"{% endif %} placeholder=">0：全显示；=0：仅对自己显示；<0：不显示" />
                                </p>
                        

                                <ul class="errorlist" id="el">
                                </ul>



                            </form>
                        </div>

                    </div>
                </div>
            </section>
        </div>
    </body>
</html>

templates/posts/posts.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8" />
        <title>{{ post_title }}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'posts/css/stylesheet.css' %} " />
        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
        <link rel="shortcut icon" href="{% static 'main/images/siteicon.ico' %}">
        <link rel="bookmark" href="{% static 'main/images/siteicon.ico' %}">
        <style>
            .editormd-html-preview {
                width: 61.8%;
                margin: 0 auto;
            }
            body {
              opacity:1.0;
            }
        </style>
        {{ extra_styles | safe }}
    </head>
    <body>
        {% if use_md%}
        <div id="layout">
            <div id="test-editormd-view" style="display:none">
               <textarea name="test-editormd-markdown-doc">{{ post_content | safe}}
               </textarea>
            </div>

        </div>
        
        <script src="{% static 'main/js/jquery.js' %} "></script>
        <script src="{% static 'editor/lib/marked.min.js' %}"></script>
        <script src="{% static 'editor/lib/prettify.min.js' %}"></script>

        <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
        <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
        <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
        <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
        <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>

        <script src="{% static 'editor/editormd.js' %}"></script>
        <script type="text/javascript">
            $(function() {
                var testEditormdView1;
                testEditormdView = editormd.markdownToHTML("test-editormd-view", {
                        // htmlDecode      : true,
                        htmlDecode      : "style,script",
                        atLink    : false,
                        emailLink : false, 
                        //toc             : false,
                        tocm            : true,
                        //tocContainer    : "#custom-toc-container",
                        //gfm             : false,
                        //tocDropdown     : true,
                        // markdownSourceCode : true,
                        emoji           : true,
                        taskList        : true,
                        tex             : true,  // 默认不解析
                        flowChart       : true,  // 默认不解析
                        sequenceDiagram : true,  // 默认不解析
                    });

            });
        </script>
        {% endif %}
        

        {{ additional_scripts | safe }}

        {% if discuss_allowed%}
            <div id="disqus_thread" style="width:61.8%;margin:0px auto"></div>
        
        <script>
            

        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
        /*
        var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        */
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://zhys-site.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <script id="dsq-count-scr" src="//zhys-site.disqus.com/count.js" async></script>
        {% endif %}
        <script> $(document).ready(function(){$('#test-editormd-view').delay(0).show();}); </script>
    </body>
</html>