src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as mviews
from editor import views as eviews
from files import views as fviews
from posts import views as pviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', mviews.index, name='index'),
    path('home/', mviews.home, name='home'),
    path('upnav/', mviews.refreshNav, name='nav'),
    path('uptagednav/', mviews.refreshtagedNav, name='tagednav'),
    path('upsearchnav/<path:cont>', mviews.refreshsearchNav, name='searcgnav'),
    path('upfile/', fviews.uploadPage, name='uploadpage'),
    path('download/<path:fp>', fviews.downFiles, name='download'),
    path('upload/', fviews.upload, name='upload'),
    path('files/<path:fp>/', fviews.viewFiles, name='viewfiles'),
    path('removefile/<path:fp>/', fviews.removeFile, name='removefile'),
    path('updatefile/<path:fp>/', fviews.updateFile, name='updatefile'),
    path('setpost/', pviews.setPost, name='setpost'),
    path('updatepost/<path:fp>/', pviews.updatePost, name='updatepost'),
    path('removepost/<path:fp>/', pviews.removePost, name='removepost'),
    path('validpost/', pviews.validPost, name='validpost'),
    path('savecache/', pviews.saveCache, name='savecache'),
    path('posts/', include('posts.urls')),
    path('preview/<path:route>', mviews.preview, name='preview'),
    path('preview_table/<path:route>', mviews.preview_table, name='preview_table'),
    path('edit/', include('editor.urls')),
]

src/files/urls.py
from django.urls import path
from . import views

app_name = 'files'
urlpatterns = [
]

src/files/models.py
from django.db import models

# Create your models here.

class myFile(models.Model):
    fname = models.CharField(
        max_length=100,
        help_text='Required. 100 characters or fewer.',
    )

    fowner = models.CharField(
        max_length=200,
        help_text='Required. 200 characters or fewer.',
        default='admin',
    )

    fviewers = models.CharField(
        max_length=200,
        help_text='Required. 200 characters or fewer. Use `public` for all users.',
        default='private',
    )
    ftags = models.CharField(
        max_length=200,
        default='',
    )
    ffeature = models.CharField(
        max_length=20,
        default='default',
    )
    fdate = models.CharField(
        max_length=8,
    )
    furl = models.CharField(
        max_length=300,
        primary_key=True,
    )
    fpass = models.CharField(
        max_length=100,
        default='',
        blank=True
    )
    frank = models.IntegerField(
        default=0,
    )
    ftrace = models.IntegerField(
        default=1
    )

src/files/forms.py
from django import forms

class UploadForm(forms.Form):
    fviewers = forms.CharField(max_length=200)
    ufile = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    fname = forms.CharField(max_length=200, required=False)
    ftags = forms.CharField(max_length=200)
    ffeature = forms.CharField(max_length=20)
    foverlap = forms.BooleanField(required=False)
    fpass = forms.CharField(max_length=100, required=False)
    frank = forms.IntegerField()
    ftrace = forms.IntegerField()

src/files/views.py
#coding:utf-8
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseNotFound, HttpResponse
import os
# Create your views here.
import core
from .forms import UploadForm
from .models import myFile
file_basedir = os.path.join(os.path.dirname(core.settings.BASE_DIR), 'filebase/')
import time
import mimetypes


from django.views.decorators.csrf import csrf_exempt

def getDate():
    return time.strftime("%Y%m%d")

def handle_upload(request, form, rfile):
    info=None
    if rfile==None:
        rfilename = form.cleaned_data.get('fname')
    else:
        rfilename = rfile.name
    if rfilename=='':
        return None, False
    try:
        info = myFile()
        info.fowner = request.user.username
        info.fdate = getDate()
        info.ffeature = form.cleaned_data.get('ffeature')
        info.fname = rfilename
        info.fviewers = form.cleaned_data.get('fviewers')
        info.ftags = form.cleaned_data.get('ftags')
        info.fpass = form.cleaned_data.get('fpass')
        info.frank = form.cleaned_data.get('frank')
        info.ftrace = form.cleaned_data.get('ftrace')
        info.furl = '%s/%s/%s'%(info.fowner, info.ffeature, info.fname)
    except Exception:
        return None, False
    return info, True

def savefilelcally(request, info, rfile):
    pdir1 = os.path.join(file_basedir, info.fowner)
    if not os.path.exists(pdir1):
        try:
            os.mkdir(pdir1)
        except Exception:
            return False, u'保存文件时出错，请联系管理员。'
    pdir2 = os.path.join(pdir1, info.ffeature)
    if not os.path.exists(pdir2):
        try:
            os.mkdir(pdir2)
        except Exception:
            return False, u'保存文件时出错，请联系管理员。'
    pf = os.path.join(pdir2, info.fname)
    try:
        with open(pf, 'wb+') as destination:
            for chunk in rfile.chunks():
                destination.write(chunk)
    except Exception:
        return False, u'保存文件时出错，请联系管理员。'

    if info.fpass=='':
        return True, u'上传成功，链接http://%s/files/%s'%(request.META['HTTP_HOST'], info.furl)
    else:
        return True, u'上传成功，链接http://%s/files/%s\n 免密链接http://%s/files/%s?pass=%s\n\n'%(request.META['HTTP_HOST'], info.furl, request.META['HTTP_HOST'], info.furl, info.fpass)

def uploadPage(request):
    return render(request, 'files/upload.html', context={'have_source':False})


def upload(request):
    ret = {'success':False, 'message':''}
    if not request.user.is_authenticated:
        ret['message']=u'你尚未登录，请转到主页登录后操作。'
    else:
        if request.method == 'POST':
            form = UploadForm(request.POST, request.FILES)
            if form.is_valid():
                flist =  request.FILES.getlist('ufile')
                if len(flist)==0:
                    info, ret['success'] = handle_upload(request, form, None)
                    if not ret['success']:
                        ret['message']=u'保存信息时出错，请确认选择了上传的文件或指定了修改的文件。'
                    else:
                        info.save()
                        ret['message']=u'修改成功！'
                else:
                    ret['success']=True
                    infos = []
                    for ufile in flist:
                        is_success = False
                        info, is_success = handle_upload(request, form, ufile)
                        if not is_success:
                            ret['success']=False
                            ret['message']+=u'保存文件%s信息时出错，请核对信息后联系管理员。\n'%(ufile.name)
                        infos.append(info)
                    if ret['success']:
                        if not form.cleaned_data.get('foverlap'):
                            for info, ufile in zip(infos, flist):
                                try:
                                    myFile.objects.get(furl=info.furl)
                                    ret['success']=False
                                    ret['message']+=u'文件%s已存在，如需更新请勾选overlap选项。\n'%(info.fname)
                                except Exception:
                                    pass
                        if ret['success']:
                            for info, ufile in zip(infos, flist):
                                info.save()
                                is_success, tmp_message = savefilelcally(request, info, ufile)
                                ret['success'] = ret['success'] and is_success
                                ret['message'] += tmp_message
            else:
                ret['message']=u'请确认选择了合适的文件，并填写了可见的用户(至少为private)；如果填写没有问题，请联系管理员排查错误。'
        else:
            ret = {'message', 'Stop hacking me!'}
    return JsonResponse(ret)


from django.http import StreamingHttpResponse
def file_iterator(file_name, chunk_size=512):
    with open(file_name, 'rb') as f:
        while True:
            c = f.read(chunk_size)
            if c:
                yield c
            else:
                break

def download(request, fp, force_att=True, is_resume=False):
    try:
        myfile = myFile.objects.get(furl=fp)
    except Exception:
        return HttpResponseNotFound()
    viewers = set(myfile.fviewers.split())
    owner = myfile.fowner
    if (is_resume or 'unlimited' in viewers or request.user.is_authenticated and ('public' in viewers or request.user.username in viewers or request.user.username==owner)):
        response = None
        try:
            file_path = os.path.join(file_basedir, fp)
            fsock = open(file_path,"rb")
            file_name = os.path.basename(file_path)
            file_size = os.path.getsize(file_path)
            if is_resume or request.user.is_authenticated and request.user.username==owner or myfile.fpass=="" or (request.method == 'POST' and request.POST['pass']==myfile.fpass) or (request.method == 'GET' and 'pass' in request.GET and request.GET['pass']==myfile.fpass):
                mime_type_guess = mimetypes.guess_type(file_name)
                if mime_type_guess[0] == None:
                    mime_type_guess = ('application/octet-stream')
                # response = HttpResponse(fsock, content_type=mime_type_guess[0])
                # response = StreamingHttpResponse(file_iterator(file_path))
                canseelist = ['.txt', '.js', '.py', '.c', '.cpp', '.java', '.py', '.md', '.html', '.htm', '.css', '.pdf', '.jpg', '.bmp', 'png', 'mp4', 'gif', 'svg']
                cansee = False
                for su in canseelist:
                    if fp.lower().endswith(su):
                        cansee = True
                        break
                if force_att or not cansee:
                    response = StreamingHttpResponse(file_iterator(file_path))
                    response['Content-Type'] = 'application/octet-stream'
                    response['Content-Disposition'] = 'attachment; filename=' + file_name
                else:
                    response = HttpResponse(fsock, content_type=mime_type_guess[0])
                    response['Content-Disposition'] = 'filename=' + file_name
            elif request.method == 'POST':
                response = render(request, 'files/file_passwd.html', context={'file_title':file_name, 'request_url':request.path, 'addtional_info':'验证信息有误！'})
            else:
                response = render(request, 'files/file_passwd.html', context={'file_title':file_name, 'request_url':request.path, 'addtional_info':''})
        except IOError:
            response = HttpResponseNotFound()
    else:
        response = HttpResponseNotFound()
    return response

def viewFiles(request, fp):
    return download(request, fp, force_att=False)
def downFiles(request, fp):
    return download(request, fp, force_att=True)

@csrf_exempt
def removeFile(request, fp):
    response = {'message':'', 'success':False}
    if request.method == 'POST':
        if request.user.is_authenticated:
            try:
                myfile = myFile.objects.get(furl=fp)
            except Exception:
                response['message'] = u'文件已失效或不存在'
                return JsonResponse(response)

            owner = myfile.fowner
            fname = myfile.fname
            if owner==request.user.username:
                try:
                    myfile.delete()
                    file_path = os.path.join(file_basedir, fp)
                    os.remove(file_path)
                except Exception as e:
                    try:
                        myFile.objects.get(furl=fp)
                    except Exception:
                        response['message'] = fname
                        response['success'] = True
                    else:
                        response['message'] = u'删除出错，请联系管理员'
                response['message'] = fname
                response['success'] = True

        else:
            response['message'] = u'请登录后操作！'
    else:
        response['message'] = u''
    return JsonResponse(response)

def updateFile(request, fp):
    if request.user.is_authenticated:
        try:
            myfile = myFile.objects.get(furl=fp)
        except Exception:
            return HttpResponseNotFound
        owner = myfile.fowner
        if request.user.username==owner:
            file_name = myfile.fname
            feature_name = myfile.ffeature
            file_viewers = myfile.fviewers
            file_tags = myfile.ftags
            file_pass = myfile.fpass
            file_rank = myfile.frank
            file_trace = myfile.ftrace
            return render(request, 'files/upload.html', context={'have_source':True, 'source_fname':file_name, 'source_ffeature':feature_name, 'file_viewers':file_viewers, 'file_tags':file_tags, 'file_pass':file_pass, 'file_rank':file_rank, 'file_trace':file_trace})
        else:
            return HttpResponseNotFound
    else:
        return redirect("/users/login/")

templates/files/file_passwd.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8" />
        <title>{{ file_title }}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'posts/css/stylesheet.css' %} " />
        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
        <link rel="shortcut icon" href="{% static 'main/images/siteicon.ico' %}">
        <link rel="bookmark" href="{% static 'main/images/siteicon.ico' %}">
        <style>
            .editormd-html-preview {
                width: 61.8%;
                margin: 0 auto;
            }
            body {
              opacity:1.0;
            }
        </style>
    </head>
    <body>
        <script src="{% static 'main/js/jquery.js' %} "></script>

        <form action="" method="POST" style="display:none" id="forward_form">
            {% csrf_token %}
            <textarea name="pass" id="pass_ele"> </textarea>
        </form>
        <script>
            function StandardPost(url,pass){
                var temp_form = document.getElementById("forward_form");
                temp_form.action = url;
                var opt = document.getElementById("pass_ele");
                opt.value = pass;
                temp_form.appendChild(opt);
                temp_form.submit();
            }
            var r=prompt("{{ addtional_info }} 请输入文件所有者提供的验证信息：", "");
            if (r){
                StandardPost('{{ request_url | safe }}',r);
            }
        </script>

    </body>
</html>

templates/files/upload.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
        <title>Upload</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Upload Form" />
        <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
        <meta name="author" content="Codrops" />
        <link rel="shortcut icon" href="{% static 'main/images/siteicon.ico' %}">
        <link rel="bookmark" href="{% static 'main/images/siteicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'users/css/demo.css' %} "/>
        <link rel="stylesheet" type="text/css" href="{% static 'users/css/style3.css' %} " />
		<link rel="stylesheet" type="text/css" href="{% static 'users/css/animate-custom.css' %} " />
        <style>
        .errorlist {
            color: red;
        }
        </style>
		<script src="{% static 'main/js/jquery.js' %} "></script>
        <script>
            function try_up(){
                $(document).ready(function(){
                    var formData = new FormData($('#up_form')[0]);
                    $('#el').html('Uploading~');
                    $.ajax({
                            type: "POST",
                            url: "{% url 'upload' %}",
                            data: formData,
                            contentType: false,
                            processData: false,
                            success: function (ret) {
                                $('#el').html(ret['message']);
                                return false;
                        }
                    })
                });
            }
        </script>
    </head>
    <body>
        <div class="container">
            <!-- Codrops top bar -->
            <div class="codrops-top">
                <span class="right">

                </span>
                <div class="clr"></div>
            </div><!--/ Codrops top bar -->
            <section>
                <div id="container_demo" >
                    <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
                    <div id="wrapper">
                        <div id="register" class="animate form">
                            <form id="up_form">
                                <h1> Upload File </h1>
                                {% csrf_token %}
                                <p>
                                    {% if have_source %}
                                    <label for="id_fname" class="uname" data-icon="e">文件名：</label>
                                    <input id="id_fname" name="fname" required="required" type="text" value="{{source_fname}}" placeholder="文件名，不需要上传文件了。" readonly="readonly"/>
                                    {% else %}
                                    <input type="file" name="ufile" id="id_ufile" multiple required="required"/>
                                    {% endif %}
                                </p>
                                <p>
                                    <label for="id_ffeature" class="uname" data-icon="e">主题:</label>
                                    {% if have_source %}
                                    <input id="id_ffeature" name="ffeature" required="required" type="text" value="{{source_ffeature}}" placeholder="文章标识，同名文章就用这个来区分了。" readonly="readonly"/>
                                    {% else %}
                                    <input id="id_ffeature" name="ffeature" required="required" type="text" value="default" placeholder="文章标识，同名文章就用这个来区分了。" />
                                    {% endif %}
                                </p>
                                <p>
                                    <label for="id_fviewers" class="uname" data-icon="u">文件权限:</label>
                                    <input id="id_fviewers" name="fviewers" required="required" type="text"    value={% if have_source %}"{{ file_viewers }}"{% else %}"public"{% endif %} placeholder="自己:`private`，公开:`public`，其他人:用户名，多种设置用空格隔开" />
                                <p>
                                    <label for="id_ftags" class="uname" data-icon="u">标签:</label>
                                    <input id="id_ftags" name="ftags" type="text" value={% if have_source %}"{{ file_tags }}"{% else %}"null"{% endif %} placeholder="给文件一些标签，方便自己归类，多个tag用竖线|隔开。" />
                                </p>

                                <p class="keeplogin">
                                    {% if have_source %}
                                    <input type="checkbox" name="foverlap" id="id_foverlap" checked="checked" style="opacity:0; position:absolute; left:9999px;"/>
                                    {% else %}
                                    <input type="checkbox" name="foverlap" id="id_foverlap"/>
                                    <label for="id_foverlap">Overlap(是要更新上面的文件吗？)</label>
                                    {% endif %}
                                </p>

                                <p class="signin button" >
                                    <img src="{% static 'main/images/submit_button.png' %}" height=auto width=30% onmousedown="try_up()">
                                </p>

                                <p>
                                    <label for="id_fpass" class="youpass" data-icon="p">验证码:</label>
                                    <input id="id_fpass" name="fpass" type="text" value={% if have_source %}"{{ file_pass }}"{% else %}""{% endif %} placeholder="如不需要密码，则不设置" />
                                </p>
                                <p>
                                    <label for="id_frank" class="uname" data-icon="u">排序优先级:</label>
                                    <input id="id_frank" name="frank" type="text" value={% if have_source %}"{{ file_rank }}"{% else %}"0"{% endif %} placeholder="默认0，越大越靠前" />
                                </p>
                                <p>
                                    <label for="id_ftrace" class="uname" data-icon="u">导航显示:</label>
                                    <input id="id_ftrace" name="ftrace" type="text" value={% if have_source %}"{{ file_trace }}"{% else %}"1"{% endif %} placeholder=">0：全显示；=0：仅对自己显示；<0：不显示" />
                                </p>
                                
                                
                                <ul class="errorlist" id="el">
                                </ul>


                                

                            </form>
                        </div>

                    </div>
                </div>
            </section>
        </div>
    </body>
</html>