src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as mviews
from editor import views as eviews
from files import views as fviews
from posts import views as pviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', mviews.index, name='index'),
    path('home/', mviews.home, name='home'),
    path('upnav/', mviews.refreshNav, name='nav'),
    path('uptagednav/', mviews.refreshtagedNav, name='tagednav'),
    path('upsearchnav/<path:cont>', mviews.refreshsearchNav, name='searcgnav'),
    path('upfile/', fviews.uploadPage, name='uploadpage'),
    path('download/<path:fp>', fviews.downFiles, name='download'),
    path('upload/', fviews.upload, name='upload'),
    path('files/<path:fp>/', fviews.viewFiles, name='viewfiles'),
    path('removefile/<path:fp>/', fviews.removeFile, name='removefile'),
    path('updatefile/<path:fp>/', fviews.updateFile, name='updatefile'),
    path('setpost/', pviews.setPost, name='setpost'),
    path('updatepost/<path:fp>/', pviews.updatePost, name='updatepost'),
    path('removepost/<path:fp>/', pviews.removePost, name='removepost'),
    path('validpost/', pviews.validPost, name='validpost'),
    path('savecache/', pviews.saveCache, name='savecache'),
    path('posts/', include('posts.urls')),
    path('preview/<path:route>', mviews.preview, name='preview'),
    path('preview_table/<path:route>', mviews.preview_table, name='preview_table'),
    path('edit/', include('editor.urls')),
]

src/editor/urls.py
from django.urls import path
from . import views

app_name = 'editor'
urlpatterns = [
    path('<path:fp>/', views.mainpage, name='editor'),
]

src/editor/models.py
from django.db import models

# Create your models here.

src/posts/forms.py
from django import forms

class PostInfoForm(forms.Form):
    powner = forms.CharField(max_length=200)
    pname = forms.CharField(max_length=200)
    pviewers = forms.CharField(max_length=200)
    peditors = forms.CharField(max_length=200)
    ptags = forms.CharField(max_length=200)
    pfeature = forms.CharField(max_length=20)
    pcontent = forms.CharField(max_length=65535, required=False)
    poverlap = forms.BooleanField(required=False)
    ppass = forms.CharField(max_length=100, required=False)
    prank = forms.IntegerField()
    ptrace = forms.IntegerField()

src/editor/views.py
from django.shortcuts import render
from posts.views import getPosts, getCachedPosts
from django.http import JsonResponse, HttpResponseNotFound, HttpResponseForbidden, HttpResponse
# Create your views here.

def mainpage(request, fp):
    # judge whether the user and file are right.
    answer = getPosts(request, fp)
    pcache = getCachedPosts(request, fp)
    answer['post_cache']=pcache
    if answer['success'] == 0:
        return HttpResponseForbidden()
    elif answer['success'] == 1:
        return HttpResponseNotFound()
    else:
        return render(request, 'editor/editor.html', context=answer)

templates/editor/editor.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>

      <meta charset='utf-8'>
      <meta http-equiv="X-UA-Compatible" content="chrome=1">
      <link rel="shortcut icon" href="{% static 'main/images/siteicon.ico' %}">
      <link rel="bookmark" href="{% static 'main/images/siteicon.ico' %}">

      <script src="{% static 'editor/js/modernizr.js' %}"></script>
      <link rel="stylesheet" href="{% static 'editor/css/editormd.min.css' %}">
      <title>{{post_title}}</title>
      <style>
      .errorlist {
          color: red;
      }
      </style>
    </head>

  <body>
    {% if user.is_authenticated %}
    <form id="up_form" style="display:none">
        {% csrf_token %}
        <p>
            <input id="id_powner" name="powner" type="text" value="{{ post_owner }}" />
        </p>
        <p>
            <input id="id_pname" name="pname" type="text" value="{{ post_title }}" />
        </p>
        <p>
            <input id="id_pviewers" name="pviewers" type="text" value="{{ post_viewers }}" />
        </p>
        <p>
            <input id="id_peditors" name="peditors" type="text" value="{{ post_editors }}" />
        </p>
        <p>
            <input id="id_ptags" name="ptags" type="text" value="{{ post_tags }}" />
        </p>
        <p>
            <input id="id_pfeature" name="pfeature" type="text" value="{{ post_feature }}" />
        </p>
        <p>
                <input id="id_pass" name="ppass" type="password" value="{{ post_pass }}" />
        </p>
        <p>
                <input id="id_prank" name="prank" type="text" value="{{ post_rank }}" />
        </p>
        <p>
                <input id="id_ptrace" name="ptrace" type="text" value="{{ post_trace }}" />
        </p>
        <p>
            <textarea id="id_pcontent" name="pcontent" type="text" value=""/>{{ post_content | safe }}</textarea>
            <textarea id="id_pcache" name="pcache" type="text" value=""/>{{ post_cache | safe }}</textarea>
        </p>
        <p class="keeplogin">
            <input type="checkbox" name="poverlap" id="id_poverlap" checked="checked"/>
        </p>
    </form>
    <div id="content-wrapper">
        <div id="editormd">
        </div>
    </div>
    {% else %}
    <p>Please <a href="{% url 'login' %}" target="_top">login</a></p>
    {% endif %}
    <script src="{% static 'editor/js/jquery.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>
    <script src="{% static 'editor/js/editor.js' %}"></script>
  </body>
</html>