src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as mviews
from editor import views as eviews
from files import views as fviews
from posts import views as pviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', mviews.index, name='index'),
    path('home/', mviews.home, name='home'),
    path('upnav/', mviews.refreshNav, name='nav'),
    path('uptagednav/', mviews.refreshtagedNav, name='tagednav'),
    path('upsearchnav/<path:cont>', mviews.refreshsearchNav, name='searcgnav'),
    path('upfile/', fviews.uploadPage, name='uploadpage'),
    path('download/<path:fp>', fviews.downFiles, name='download'),
    path('upload/', fviews.upload, name='upload'),
    path('files/<path:fp>/', fviews.viewFiles, name='viewfiles'),
    path('removefile/<path:fp>/', fviews.removeFile, name='removefile'),
    path('updatefile/<path:fp>/', fviews.updateFile, name='updatefile'),
    path('setpost/', pviews.setPost, name='setpost'),
    path('updatepost/<path:fp>/', pviews.updatePost, name='updatepost'),
    path('removepost/<path:fp>/', pviews.removePost, name='removepost'),
    path('validpost/', pviews.validPost, name='validpost'),
    path('savecache/', pviews.saveCache, name='savecache'),
    path('posts/', include('posts.urls')),
    path('preview/<path:route>', mviews.preview, name='preview'),
    path('preview_table/<path:route>', mviews.preview_table, name='preview_table'),
    path('edit/', include('editor.urls')),
]

src/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.register, name='signup'),
]

src/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    comment = models.CharField(max_length=100, blank=True)
    proflle = models.CharField(max_length=300, default="/static/main/images/anony.png")


    class Meta(AbstractUser.Meta):
        pass

src/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User

class RegisterForm(UserCreationForm):
    profile = forms.CharField(max_length=300)
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "profile")

src/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.http import HttpResponseNotFound

def register(request):
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            if redirect_to:
                return redirect(redirect_to)
            else:
                return redirect('/')
    else:
        form = RegisterForm()

    return render(request, 'users/signup.html', context={'form': form, 'next': redirect_to})

templates/users/signup.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
        <title>Sign Up</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Registration Form" />
        <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
        <meta name="author" content="Codrops" />
        <link rel="shortcut icon" href="{% static 'main/images/siteicon.ico' %}">
        <link rel="bookmark" href="{% static 'main/images/siteicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'users/css/demo.css' %} "/>
        <link rel="stylesheet" type="text/css" href="{% static 'users/css/style3.css' %} " />
		<link rel="stylesheet" type="text/css" href="{% static 'users/css/animate-custom.css' %} " />
        <style>
        .errorlist {
            color: red;
        }
    </style>
    </head>
    <body>
        <div class="container">
            <!-- Codrops top bar -->
            <div class="codrops-top">
                <span class="right">

                </span>
                <div class="clr"></div>
            </div><!--/ Codrops top bar -->
            <section>
                <div id="container_demo" >
                    <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
                    <div id="wrapper">
                        <div id="register" class="animate form">
                            <form  action="{% url 'users:signup' %}?next={{next}}" method="POST" autocomplete="on">
                                <h1> Sign up </h1>
                                {% csrf_token %}
                                <p>
                                    <label for="id_username" class="uname" data-icon="u">Your username</label>
                                    <input id="id_username" name="username" required="required" type="text" placeholder="mysuperusername690" />
                                </p>
                                <p>
                                    <label for="id_email" class="youmail" data-icon="e" > Your email</label>
                                    <input id="id_email" name="email" required="required" type="email" placeholder="mysupermail@mail.com"/>
                                </p>
                                <p>
                                    <label for="id_password1" class="youpasswd" data-icon="p">Your password </label>
                                    <input id="id_password1" name="password1" required="required" type="password" placeholder="eg. X8df!90EO"/>
                                </p>
                                <p>
                                    <label for="id_password2" class="youpasswd" data-icon="p">Please confirm your password </label>
                                    <input id="id_password2" name="password2" required="required" type="password" placeholder="eg. X8df!90EO"/>
                                </p>
                                <p>
                                    <label for="id_profile" class="youmail" data-icon="u" > Your Avatar</label>
                                    <input id="id_profile" name="profile"  placeholder="the link of you avatar (jpg/png/gif/bmp)" value="/static/main/images/anony.png"/>
                                </p>

                                {% for field in form %}
                                {{ field.errors }}
                                {% endfor %}

                                <p class="signin button">
									<input type="submit" value="Sign up"/>
								</p>
                                <p class="change_link">
									Already a member ?
									<a href="{% url 'login' %}?next={{next}}" class="to_register"> Go and log in </a>
								</p>
                                <input type="hidden" name="next" value="{{ next }}"/>
                            </form>
                        </div>

                    </div>
                </div>
            </section>
        </div>
    </body>
</html>